version: '3.8'
services:
  rest-soap-interlayer:
    container_name: r-s-i-docker
    build: .
    image: rsi-compose:latest
    ports:
      - "8080:8080"
      - "5005:5005" # Port for Remote Debugger
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    networks:
      - my-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my-network

volumes:
  mongodb_data:

networks:
  my-network:
    driver: bridge
